// src/components/StudyGuidePaywallScreen.tsx
// Paywall/preview screen shown when Study Guide is not yet activated.
// Displayed instead of StudyPlanCard while ACTIVE_LAUNCH_FEATURES.studyGuide is false.

interface StudyGuidePaywallScreenProps {
  onBack?: () => void;
}

export default function StudyGuidePaywallScreen({ onBack }: StudyGuidePaywallScreenProps) {
  return (
    <div className="editorial-surface max-w-2xl mx-auto p-6 sm:p-8 space-y-6">
      {/* Header */}
      <div>
        {onBack && (
          <button
            onClick={onBack}
            className="mb-4 text-xs font-bold uppercase tracking-widest text-slate-400 hover:text-slate-600 transition-colors"
          >
            ← Back
          </button>
        )}
        <p className="text-xs font-black uppercase tracking-widest text-amber-700 mb-2">Study Guide</p>
        <h1 className="text-2xl font-black text-slate-900">AI Study Guide</h1>
        <p className="mt-2 text-slate-600 leading-relaxed">
          Your personalized study guide is generated by AI using your actual performance data —
          not a template, but a plan built from your skill scores, misconceptions, and readiness level.
        </p>
      </div>

      {/* What's included bullets */}
      <div>
        <h2 className="text-sm font-bold text-slate-700 mb-3">What's included</h2>
        <ul className="space-y-2 text-sm text-slate-600">
          {[
            "Readiness snapshot across all 45 skills",
            "Priority skill clusters — ranked by urgency and current gap",
            "Domain-level study maps with targeted practice recommendations",
            "Vocabulary fluency section for key terms in each priority skill",
            "Case pattern examples tied to your weakest application skills",
            "A week-by-week 14-session study schedule",
            "Checkpoint logic for self-assessment progress milestones",
          ].map((item) => (
            <li key={item} className="flex items-start gap-2">
              <span className="mt-0.5 text-amber-600">✓</span>
              {item}
            </li>
          ))}
        </ul>
      </div>

      {/* Pricing card */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-5">
        <div className="flex items-baseline gap-2 mb-2">
          <span className="text-3xl font-black text-slate-900">$5</span>
          <span className="text-sm text-slate-500">one-time activation</span>
        </div>
        <p className="text-sm text-slate-600 leading-relaxed mb-4">
          The $5 fee covers the AI generation cost — this is not a subscription.
          Once activated, your study guide is yours and can be regenerated as your performance data improves
          (up to once every 7 days).
        </p>
        <button
          disabled
          className="w-full rounded-lg bg-slate-300 px-4 py-3 text-sm font-bold text-slate-500 cursor-not-allowed"
        >
          Activate Study Guide — $5
          <span className="ml-2 text-xs font-normal">(Coming soon)</span>
        </button>
        <p className="mt-2 text-center text-xs text-slate-400">
          Payment processing coming soon — check back shortly.
        </p>
      </div>
    </div>
  );
}
