// src/data/skillPrereqGraph.ts
//
// Machine-readable prerequisite dependency graph extracted from skill-phase-d.json.
//
// Source: `skill_prerequisites` prose for each skill. Only explicit skill ID
// references (pattern [A-Z]{2,3}-\d{2}) are captured — skills without
// named prerequisites have an empty array.
//
// Generated by: reading skill-phase-d.json and regex-extracting all `[A-Z]{2,3}-\d{2}`
// tokens from each skill's `skill_prerequisites` field, excluding self-references.

export const prereqGraph: Record<string, string[]> = {
  "ACA-02": [],
  "ACA-03": [],
  "ACA-04": [],
  "ACA-06": [],
  "ACA-07": [],
  "ACA-08": [],
  "ACA-09": [],
  "CON-01": [],
  "CON-02": [],
  "CON-03": [],
  "CON-04": [],
  "CON-05": [],
  "DBD-01": [],
  "DBD-02": [],
  "DBD-03": [],
  "DBD-04": [],
  "DBD-05": ["DBD-02"],
  "ETH-01": [],
  "ETH-02": ["ETH-01"],
  "ETH-03": ["ETH-01", "ETH-02"],
  "FAM-01": [],
  "FAM-02": [],
  "FAM-03": ["FAM-02"],
  "LEG-01": ["ETH-01"],
  "LEG-02": ["ETH-01", "ETH-02", "LEG-01"],
  "LEG-03": ["LEG-02"],
  "LEG-04": ["LEG-02"],
  "MBH-01": [],
  "MBH-02": [],
  "MBH-03": [],
  "MBH-04": ["MBH-03"],
  "PRV-01": [],
  "PRV-02": [],
  "PRV-03": [],
  "SAF-01": [],
  "SAF-02": [],
  "SAF-03": ["MBH-02", "SWP-01"],
  "SAF-04": ["SAF-03", "MBH-02", "MBH-03"],
  "SLD-01": [],
  "SLD-02": [],
  "SLD-03": [],
  "SWP-01": [],
  "SWP-02": ["SWP-01"],
  "SWP-03": ["SWP-02"],
  "SWP-04": ["SWP-01", "SWP-02", "SWP-03"],
};

/**
 * Returns the total number of unique prerequisite skills that `skillId` depends
 * on, counting transitively (breadth-first, cycle-safe).
 *
 * - 0 = foundational skill (no prerequisites)
 * - Higher = more advanced skill that should appear later in the learning path
 */
export function getPrereqDepth(
  skillId: string,
  graph: Record<string, string[]> = prereqGraph,
): number {
  const visited = new Set<string>();
  const queue = [...(graph[skillId] ?? [])];

  while (queue.length > 0) {
    const current = queue.shift()!;
    if (visited.has(current)) continue;
    visited.add(current);
    const next = graph[current] ?? [];
    queue.push(...next);
  }

  return visited.size;
}
